### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by harleyday** [kei-q/revealjs-preview#17]
I have no idea why this failed.

I'm running:

- Windows 10 version 1803, build 17134.112

I would provide other information, but I don't know how to interrogate Atom at the moment. Please let me know if you need any aditional information.

Here is the complete error report from Atom.
```
> runas@3.1.1 install C:\Users\hd1213\AppData\Local\Temp\apm-install-dir-118616-14256-xbu1j5.ia0jft7qfr\node_modules\revealjs-preview\node_modules\runas
> node-gyp rebuild


C:\Users\hd1213\AppData\Local\Temp\apm-install-dir-118616-14256-xbu1j5.ia0jft7qfr\node_modules\revealjs-preview\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\hd1213\AppData\Local\atom\app-1.28.1\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\hd1213\AppData\Local\atom\app-1.28.1\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\hd1213\AppData\Local\Temp\apm-install-dir-118616-14256-xbu1j5.ia0jft7qfr\node_modules\revealjs-preview\node_modules\runas\build\binding.sln]
C:\Users\hd1213\AppData\Local\Temp\apm-install-dir-118616-14256-xbu1j5.ia0jft7qfr
`-- (empty)


npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated express@2.5.11: express 2.x series is deprecated
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
npm WARN deprecated formidable@1.0.17: Old versions of Formidable are not compatible with the current Node.js; Upgrade to 1.2.0 or later
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\hd1213\AppData\Local\atom\app-1.28.1\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\hd1213\\AppData\\Local\\atom\\app-1.28.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\hd1213\\AppData\\Local\\atom\\app-1.28.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\hd1213\AppData\Local\Temp\apm-install-dir-118616-14256-xbu1j5.ia0jft7qfr\node_modules\revealjs-preview\node_modules\runas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\hd1213\AppData\Local\Temp\apm-install-dir-118616-14256-xbu1j5.ia0jft7qfr\package.json'
npm WARN apm-install-dir-118616-14256-xbu1j5.ia0jft7qfr No description
npm WARN apm-install-dir-118616-14256-xbu1j5.ia0jft7qfr No repository field.
npm WARN apm-install-dir-118616-14256-xbu1j5.ia0jft7qfr No README data
npm WARN apm-install-dir-118616-14256-xbu1j5.ia0jft7qfr No license field.
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Users\\hd1213\\AppData\\Local\\atom\\app-1.28.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\hd1213\\AppData\\Local\\atom\\app-1.28.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\hd1213\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\hd1213\\.atom\\.apmrc" "install" "C:\\Users\\hd1213\\AppData\\Local\\Temp\\d-118616-14256-4d0efu.0nfe8tcsor\\package.tgz" "--runtime=electron" "--target=2.0.4" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hd1213\AppData\Local\Temp\apm-install-dir-118616-14256-xbu1j5.ia0jft7qfr\npm-debug.log
npm ERR! code 1
```

**Comment by walterheck** [comment]
Running into the same thing. @kei-q any ideas?
